//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.03 at 06:00:03 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/Revoche/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.gov.digitpa.schemas._2011.pagamenti.revoche;
